//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectFSS_Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int typeId { get; set; }
        public string name { get; set; }
        public decimal balance { get; set; }
    
        public virtual AccountType AccountType { get; set; }
        public virtual User User { get; set; }
    }
}
